# Generated by Django 2.2.1 on 2019-05-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='text',
            field=models.TextField(db_index=True),
        ),
    ]
